### ISSUE TITLE
SEGVで落ちる

### ISSUE THREAD

**Issue by ray45422** [ray45422/ekeymgr#10]
発生頻度が低く原因不明。
要調査

**Comment by ray45422** [comment]
coredumpをgdbにかけた
(gdb) bt
#0  0x766c4630 in thread_entryPoint () from /usr/lib/libdruntime-ldc.so.68
#1  0x76623288 in start_thread () from /usr/lib/libpthread.so.0
#2  0x764f8508 in ?? () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by ray45422** [comment]
D言語のアップデートのおかげか落ちなくなった

**Comment by ray45422** [comment]
最近頻発している
スレッド周りの見直しをしてみる
